$background = f9f9f9
$onBackground = 323232
$surface = f9f9f9
$surfaceDim = dadada
$surfaceBright = f9f9f9
$surfaceContainerLowest = ffffff
$surfaceContainerLow = f4f4f4
$surfaceContainer = eeeeee
$surfaceContainerHigh = e8e8e8
$surfaceContainerHighest = e3e3e3
$onSurface = 323232
$surfaceVariant = e3e3e3
$onSurfaceVariant = 5f5f5f
$outline = 7a7a7a
$outlineVariant = b2b2b2
$inverseSurface = 0e0e0e
$inverseOnSurface = 9d9d9d
$shadow = 000000
$scrim = 000000
$surfaceTint = 5e5e5e
$primary = 5e5e5e
$primaryDim = 525252
$onPrimary = f8f8f8
$primaryContainer = e2e2e2
$onPrimaryContainer = 515151
$inversePrimary = f6f6f6
$primaryFixed = e2e2e2
$primaryFixedDim = d5d5d5
$onPrimaryFixed = 3f3f3f
$onPrimaryFixedVariant = 5b5b5b
$secondary = 5f5f5f
$secondaryDim = 535353
$onSecondary = f9f9f9
$secondaryContainer = e3e3e3
$onSecondaryContainer = 515151
$secondaryFixed = e3e3e3
$secondaryFixedDim = d4d4d4
$onSecondaryFixed = 3f3f3f
$onSecondaryFixedVariant = 5b5b5b
$tertiary = 5f5f58
$tertiaryDim = 53534c
$onTertiary = fbf9ef
$tertiaryContainer = f5f4e9
$onTertiaryContainer = 5c5c54
$tertiaryFixed = f5f4e9
$tertiaryFixedDim = e7e6dc
$onTertiaryFixed = 4a4a43
$onTertiaryFixedVariant = 66675e
$error = 8f4c3c
$errorDim = 521d10
$onError = f9f9f9
$errorContainer = e99682
$onErrorContainer = 682e20
$primaryPaletteKeyColor = 777777
$secondaryPaletteKeyColor = 777777
$tertiaryPaletteKeyColor = 777777
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 777777
$errorPaletteKeyColor = ac6352
$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 777777
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$term0 = 9b9b9b
$term1 = 785c30
$term2 = 8b813a
$term3 = 866c35
$term4 = 9b8747
$term5 = 876332
$term6 = 7e8452
$term7 = 222222
$term8 = 0f0f0f
$term9 = 967237
$term10 = aea14f
$term11 = a58746
$term12 = bfaa66
$term13 = aa7c3a
$term14 = 9fa56f
$term15 = 282828
$rosewater = 917a51
$flamingo = 917037
$pink = a17538
$mauve = 834320
$red = 67512b
$maroon = 7d6131
$peach = 8e7237
$yellow = 947b3a
$green = 777034
$teal = 676c3c
$sky = 5b8446
$sapphire = 6f7741
$blue = 3b6153
$lavender = b25557
$klink = 6a9165
$klinkSelection = 6a9165
$kvisited = b27235
$kvisitedSelection = b27235
$knegative = a7813d
$knegativeSelection = a7813d
$kneutral = cca649
$kneutralSelection = cca649
$kpositive = b2ac46
$kpositiveSelection = b2ac46
$text = 323232
$subtext1 = 5f5f5f
$subtext0 = 7a7a7a
$overlay2 = 898989
$overlay1 = 9b9b9b
$overlay0 = ababab
$surface2 = bdbdbd
$surface1 = cfcfcf
$surface0 = e4e4e4
$base = f9f9f9
$mantle = f1f0f0
$crust = ecebea
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
