-- Generated by nwg-displays on 2026-07-30 at 16:19:25. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1366x768@75.78999999999999",
    position = "1920x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "0x101",
    scale = 1.0
})
